Train:
  batch_size: 20
  learning_rate: 10
  reg: 0.0001
  epochs: 15
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet